---
- name: Detect primary ethernet interface
  set_fact:
    interface_name: "{{ ansible_default_ipv4.interface }}"
  when: interface_name is not defined

- name: Apply Wi-Fi configuration
  become: yes
  ansible.builtin.template:
    src: templates/netplan.yaml.j2
    dest: /etc/netplan/01-netcfg.yaml
    mode: '0600'
  notify: Apply Network Config

- name: Install Podman
  become: yes
  ansible.builtin.apt:
    name: podman
    state: present
    update_cache: yes